version: 2

# Nombre de flujo de trabajo
name: despliegue en GitHub

on: 
  push:
    paths:
      - 'nginx/index.html'
# crea un ID de trabajo
jobs:
  build:
    docker:
      - image: nginx-1
    run-on: ubuntu-latest  
    steps:
        - name: chekout
          uses: actions/checkout@v2

        - setup_remote_docker:
          docker_layer_caching: true

      # Inicia sesion en Docker Hub
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      # crea la imagen del contenedor y la envia al repositorio
      - run:
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            context:
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/florenciagc:latest
      