version: 2
jobs:
  build:
    docker:
      - image: nginx-1
  
    steps:
      - run:
          name: chekout
          uses: actions/checkout@v2

      - setup_remote_docker:
          docker_layer_caching: true

      -run:
          name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run:
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: user/app:latest
      